spring:
  application:
    name: SpringMVC

  main:
    banner-mode: off

  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/avtomatika?currentSchema=public
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    open-in-view: false

server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: youralias